# First print your name in the cell below then save this file. (or something nice about your instructor)

In [29]:
# In this cell print your name 
print("Jin Wang")

Jin Wang

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [30]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [31]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [32]:
# Load data here
df = pd.read_csv('../data/listings.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [33]:
# 1. How many listings are there with a price less than 100? 
listings = df['price'] < 100
int(listings.sum())

22778

In [34]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
df_bk = df['neighbourhood_group'] == 'Brooklyn'
int(df_bk.sum())

18632

In [35]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
bk_less = df[listings & df_bk]
len(bk_less)

10473

In [36]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names

host_names = ['Micheal', 'David', 'John', 'Daniel']
condition = df.host_name.isin(host_names)
df[condition]['host_name'].value_counts()

host_name
David      348
John       270
Daniel     253
Micheal      3
Name: count, dtype: int64

In [37]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
df['adjusted_price'] = df['price']
df.loc[df['neighbourhood'] == 'Williamsburg', 'adjusted_price']+=100

In [38]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
rooms = df.room_type.value_counts(normalize=True) * 100
print('Private rooms:', f'{rooms.get('Private room'):.2f}', '%')
print('Shared rooms:', f'{rooms.get('Shared room'):.2f}', '%')

Private rooms: 45.44 %
Shared rooms: 2.12 %

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [39]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
group_by_listings = df.groupby('neighbourhood_group').size()
print(group_by_listings)

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [40]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].mean().round(2)

neighbourhood_group
Bronx             92.75
Brooklyn         120.23
Manhattan        191.88
Queens            99.75
Staten Island    110.95
Name: price, dtype: float64

In [41]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df.groupby('room_type')['price'].mean().round(2)

room_type
Entire home/apt    199.40
Hotel room         275.02
Private room        91.45
Shared room         87.06
Name: price, dtype: float64

In [42]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].agg(['min','max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [43]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
df.groupby(['neighbourhood_group','room_type'])['price'].mean().round(2)

neighbourhood_group  room_type
Bronx                Entire home/apt    138.00
                     Private room        68.42
                     Shared room         66.39
Brooklyn             Entire home/apt    171.59
                     Hotel room         147.30
                     Private room        71.29
                     Shared room         57.87
Manhattan            Entire home/apt    231.34
                     Hotel room         292.52
                     Private room       128.28
                     Shared room        111.74
Queens               Entire home/apt    150.17
                     Hotel room         139.06
                     Private room        69.97
                     Shared room         89.89
Staten Island        Entire home/apt    151.72
                     Private room        70.31
                     Shared room         46.00
Name: price, dtype: float64

In [44]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
df.groupby(['neighbourhood_group','room_type'])['price'].agg(['count','min','max','mean','median','std']).round(2)

                                     count  min    max    mean  median     std
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.00   103.0  126.03
                    Private room       722   16    700   68.42    55.0   57.34
                    Shared room         46   20    800   66.39    44.0  114.44
Brooklyn            Entire home/apt   9112   20  10000  171.59   135.0  236.73
                    Hotel room          30    0    399  147.30   129.0   91.15
                    Private room      9159   10   2500   71.29    60.0   69.02
                    Shared room        331   15   1500   57.87    36.0   92.22
Manhattan           Entire home/apt  12209    0  10000  231.34   165.0  410.31
                    Hotel room         351    0   2211  292.52   210.0  315.92
                    Private room      7601   10  10000  128.28    80.0  448.68
                    Shared room        419   10  10000  111.74    60.0  502.73
Queens              Entire home/apt   2090   10  10000  150.17   115.0  252.61
                    Hotel room          17    0    249  139.06   149.0   50.74
                    Private room      3499   18   9000   69.97    55.0  163.81
                    Shared room        185   14   3000   89.89    40.0  275.68
Staten Island       Entire home/apt    172   39   1200  151.72   111.0  147.52
                    Private room       163   20    800   70.31    55.0   70.76
                    Shared room          6   19     82   46.00    38.0   28.45

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [47]:
# 1. Load the `prices.csv` and the `n_listings.csv`
df_price = pd.read_csv('../data/prices.csv')
df_price.head()
df_n = pd.read_csv('../data/n_listings.csv', sep=';')
df_n.head()

  neighbourhood_group  n_listings
0               Bronx        1183
1            Brooklyn       18632
2           Manhattan       20580
3          LongIsland        4121

In [48]:
# 2. Do join that keeps all the records for each table.

df_joined = pd.merge(df_price, df_n, on = 'neighbourhood_group', how = 'outer')
df_joined

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN
5       Staten Island   110.947214         NaN

In [49]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
df_joined.to_csv('../data/joined.csv', index = False)

In [50]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
df_joined.head()

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.