# First print your name in the cell below then save this file. (or something nice about your instructor)

### In this cell print your name 
Rostyslav Kharevych

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [1]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [2]:
# Load data here
directory = 'data/listings.csv'
df = pd.read_csv(directory)

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [3]:
# 1. How many listings are there with a price less than 100? 
len(df[df['price'] < 100])

22778

In [10]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
df_bk = df[df['neighbourhood_group'] == 'Brooklyn'].copy().reset_index(drop=True)
len(df_bk)

18632

In [11]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
len(df_bk[df_bk['price'] < 100])

10473

In [12]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
hosts = ['Michael', 'David', 'John', 'Daniel']
df_bk['host_name'].isin(hosts).sum()

np.int64(457)

In [13]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
df_bk['adjusted_price'] = df_bk['price']
df_bk.loc[df_bk['neighbourhood'] == 'Williamsburg', 'adjusted_price']+=100
df_bk.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,75
1,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,60
2,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,175
3,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344,88
4,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0,209

In [19]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
df_bk['room_type'].value_counts()
private_prcnt = (df_bk['room_type'] == 'Private room').mean() * 100
shared_prcnt = (df_bk['room_type'] == 'Shared room').mean() * 100

print(f"Private room: {private_prcnt:.2f}%")
print(f"Shared room: {shared_prcnt:2f}%")

Private room: 49.16%
Shared room: 1.776514%

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [28]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
df.groupby('neighbourhood_group').size()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [31]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [32]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df.groupby('room_type')['price'].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [35]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [39]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].mean().unstack()

room_type            Entire home/apt  Hotel room  Private room  Shared room
neighbourhood_group
Bronx                     138.004819         NaN     68.419668    66.391304
Brooklyn                  171.587687  147.300000     71.291189    57.870091
Manhattan                 231.335572  292.515670    128.277069   111.735084
Queens                    150.168900  139.058824     69.972564    89.891892
Staten Island             151.720930         NaN     70.312883    46.000000

In [40]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819   103.0
                    Private room       722   16    700   68.419668    55.0
                    Shared room         46   20    800   66.391304    44.0
Brooklyn            Entire home/apt   9112   20  10000  171.587687   135.0
                    Hotel room          30    0    399  147.300000   129.0
                    Private room      9159   10   2500   71.291189    60.0
                    Shared room        331   15   1500   57.870091    36.0
Manhattan           Entire home/apt  12209    0  10000  231.335572   165.0
                    Hotel room         351    0   2211  292.515670   210.0
                    Private room      7601   10  10000  128.277069    80.0
                    Shared room        419   10  10000  111.735084    60.0
Queens              Entire home/apt   2090   10  10000  150.168900   115.0
                    Hotel room          17    0    249  139.058824   149.0
                    Private room      3499   18   9000   69.972564    55.0
                    Shared room        185   14   3000   89.891892    40.0
Staten Island       Entire home/apt    172   39   1200  151.720930   111.0
                    Private room       163   20    800   70.312883    55.0
                    Shared room          6   19     82   46.000000    38.0

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [83]:
# 1. Load the `prices.csv` and the `n_listings.csv`
df_prices = pd.read_csv('data/prices.csv')
df_n_listings = pd.read_csv('data/n_listings.csv')

In [90]:
df_prices.head()

  neighbourhood_group   mean_price
0               Bronx    92.751479
1            Brooklyn   120.225258
2           Manhattan   191.880466
3              Queens    99.754965
4       Staten Island   110.947214

In [85]:
df_n_listings.head()

  neighbourhood_group;n_listings
0                     Bronx;1183
1                 Brooklyn;18632
2                Manhattan;20580
3                LongIsland;4121

In [86]:
df_n_listings[['neighbourhood_group', 'n_listings']] = df_n_listings['neighbourhood_group;n_listings'].str.split(';', expand = True)
df_n_listings.drop(columns=['neighbourhood_group;n_listings'], inplace=True)
df_n_listings['n_listings'] = df_n_listings['n_listings'].astype('int64')
df_n_listings.head()

  neighbourhood_group  n_listings
0               Bronx        1183
1            Brooklyn       18632
2           Manhattan       20580
3          LongIsland        4121

In [91]:
# 2. Do join that keeps all the records for each table.
joined_csv = pd.merge(df_prices,
                      df_n_listings,
                      on = 'neighbourhood_group',
                      how = 'outer')

joined_csv.head()

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN

In [88]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
joined_csv.to_csv('data/joined.csv', index=False)

In [89]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
joined_csv_test = pd.read_csv('data/joined.csv')
joined_csv_test.head()

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

I found this package that works with Pandas at the end of the homework video "Top 25 Pandas tricks" and thought that it can be very useful during the initial Data Exploration stage and save some time. It's called ydata_profiling and it gives a quick report of the dataset:
- It gives a brief overview of the dataset and any possible issues that can be in the data
- The summary of each column with a possibility to view more detailed information about each column
- It shows a correlation heatmap between the columns

In [93]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (2.10.3)
Collecting PyYAML<6.1,>=6.0.3 (from ydata-profiling)
  Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (2.1.3)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (0.14.4)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.6.0-py3-none-any.whl.metadata (3.7 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Collecting typing-extensions>=4.12.2 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: attrs>=19.3.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (24.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-win_amd64.whl (678 kB)
   ---------------------------------------- 0.0/678.1 kB ? eta -:--:--
   --------------------------------------- 678.1/678.1 kB 27.7 MB/s eta 0:00:00
Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl (154 kB)
Downloading typeguard-4.6.0-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ---------------------------------------- 3.1/3.1 MB 38.3 MB/s eta 0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl (306 kB)
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
Installing collected packages: minify-html, filetype, typing-extensions, PyYAML, puremagic, multimethod, dacite, typeguard, imagehash, wordcloud, visions, phik, ydata-profiling

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.12.2

    Uninstalling typing_extensions-4.12.2:

   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
      Successfully uninstalled typing_extensions-4.12.2
   ------ ---------------------------------  2/13 [typing-extensions]
   ------ ---------------------------------  2/13 [typing-extensions]
  Attempting uninstall: PyYAML
   ------ ---------------------------------  2/13 [typing-extensions]
    Found existing installation: PyYAML 6.0.2
   ------ ---------------------------------  2/13 [typing-extensions]
    Uninstalling PyYAML-6.0.2:
   ------ ---------------------------------  2/13 [typing-extensions]
      Successfully uninstalled PyYAML-6.0.2
   ------ ---------------------------------  2/13 [typing-extensions]
   --------------- ------------------------  5/13 [multimethod]
   ------------------------ ---------------  8/13 [imagehash]
   ------------------------ ---------------  8/13 [imagehash]
   ------------------------------ --------- 10/13 [visions]
   ------------------------------ --------- 10/13 [visions]
   ------------------------------------ --- 12/13 [ydata-profiling]
   ------------------------------------ --- 12/13 [ydata-profiling]
   ---------------------------------------- 13/13 [ydata-profiling]

Successfully installed PyYAML-6.0.3 dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 typeguard-4.6.0 typing-extensions-4.16.0 visions-0.8.1 wordcloud-1.9.6 ydata-profiling-4.18.4

In [94]:
from ydata_profiling import ProfileReport
ProfileReport(df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 16/16 [00:00<00:00, 67.75it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [96]:
df_grammys = pd.read_csv("data/grammys.csv")
df_grammys.head()

,year,category,nominee,workers,winner
0,1959,Album of the Year,The Music from Peter Gunn.,Henry Mancini,True
1,1959,Best Album Cover,Only the Lonely,Frank Sinatra (art director),True
2,1959,Best Arrangement,The Music From Peter Gunn,Henry Mancini (artist/arranger),True
3,1959,Best Classical Performance - Chamber Music (in...,Beethoven: Quartet 130,"The Hollywood String Quartet, Paul Shure (arti...",True
4,1959,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,Andrés Segovia,True

In [100]:
df_grammys[(df_grammys['category'] == 'Album of the Year') & (df_grammys['year'] == 2016) & (df_grammys['winner'] == True)]

,year,category,nominee,workers,winner
5505,2016,Album of the Year,1989.,"Taylor Swift (artist/producer), Jack Antonoff ...",True

In [101]:
df_grammys[(df_grammys['category'] == 'Best Rap Album') & (df_grammys['year'] == 2009) & (df_grammys['winner'] == True)]

      year        category         nominee     workers  winner
4396  2009  Best Rap Album  Tha Carter III  Lil' Wayne    True

In [115]:
df_grammys[df_grammys['workers'] == "Kendrick Lamar"]['winner'].value_counts()

winner
True     4
False    2
Name: count, dtype: int64

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.