# First print your name in the cell below then save this file. (or something nice about your instructor)

In [4]:
# In this cell print your name 

name = "Salvador Cardoso"
print(f"{name}")

!pip install pandas

Salvador Cardoso
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 23.4 MB/s  0:00:00m0:00:01
Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 30.9 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.2 pandas-3.0.5

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [3]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [4]:
# Load data here
df = pd.read_csv("/workspaces/ds-fall-2026/Week-01-Pandas/data/listings.csv")
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [4]:
# 1. How many listings are there with a price less than 100?
GT100Condition =  df["price"] > 100
GT100 = df[GT100Condition].copy()
GT100.value_counts()

brooklynCondition = df["neighbourhood_group"] == "Brooklyn"
brooklyn = df[brooklynCondition].copy()
brooklyn.value_counts()

brooklynSub100Condition = (df["neighbourhood_group"] == "Brooklyn") & (df["price"] < 100)
brooklynSub100 = df[brooklynSub100Condition].copy()

In [5]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
brooklynCondition = df["neighbourhood_group"] == "Brooklyn"
df_bk = df[brooklynCondition].copy()
df_bk.value_counts()

id        name                                                host_id    host_name      neighbourhood_group  neighbourhood       latitude  longitude  room_type        price  minimum_nights  number_of_reviews  last_review  reviews_per_month  calculated_host_listings_count  availability_365
3831      Whole flr w/private bdrm, bath & kitchen(pls read)  4869       LisaRoxanne    Brooklyn             Clinton Hill        40.68514  -73.95976  Entire home/apt  75     1               340                2020-08-01   4.75               1                               265                 1
5121      BlissArtsSpace!                                     7356       Garon          Brooklyn             Bedford-Stuyvesant  40.68688  -73.95596  Private room     60     29              50                 2019-12-02   0.37               1                               365                 1
5136      Spacious Brooklyn Duplex, Patio + Garden            7378       Rebecca        Brooklyn             Sunset Park         40.66120  -73.99423  Entire home/apt  175    14              1                  2014-01-02   0.01               1                               295                 1
5803      Lovely Room 1, Garden, Best Area, Legal rental      9744       Laurie         Brooklyn             South Slope         40.66829  -73.98779  Private room     88     4               180                2020-03-18   1.31               3                               344                 1
6848      Only 2 stops to Manhattan studio                    15991      Allen & Irina  Brooklyn             Williamsburg        40.70837  -73.95352  Entire home/apt  109    2               181                2020-03-16   1.32               1                               0                   1
                                                                                                                                                                                                                                                                                                    ..
44435099  Private Room in Apartment You Can Rent in Brooklyn  358933697  Kenday         Brooklyn             East New York       40.67210  -73.87946  Private room     45     1               1                  2020-07-29   1.00               1                               344                 1
44445557  Two Bedroom Penthouse W/Balcony and Roof access     13603829   Kazi           Brooklyn             Kensington          40.63592  -73.97307  Entire home/apt  264    1               8                  2020-08-13   8.00               2                               359                 1
44461963  Newly Renovated Private Apartment                   143516082  Maria          Brooklyn             Bedford-Stuyvesant  40.68708  -73.95070  Entire home/apt  114    1               1                  2020-08-09   1.00               1                               124                 1
44609727  Private room in a big apartment in Brooklyn         310776840  Alejandra      Brooklyn             Bedford-Stuyvesant  40.69146  -73.93433  Private room     40     1               1                  2020-08-09   1.00               4                               228                 1
44633340  C.C - Brklyn Small but cozy room close to Subways   361101225  Roger          Brooklyn             Bushwick            40.68650  -73.90841  Private room     46     1               1                  2020-08-10   1.00               4                               364                 1
Name: count, Length: 14858, dtype: int64

In [8]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

brooklynSub100Condition = (df["neighbourhood_group"] == "Brooklyn") & (df["price"] < 100)
brooklynSub100 = df[brooklynSub100Condition].copy()
brooklynSub100.value_counts()

id        name                                                host_id    host_name    neighbourhood_group  neighbourhood       latitude  longitude  room_type        price  minimum_nights  number_of_reviews  last_review  reviews_per_month  calculated_host_listings_count  availability_365
3831      Whole flr w/private bdrm, bath & kitchen(pls read)  4869       LisaRoxanne  Brooklyn             Clinton Hill        40.68514  -73.95976  Entire home/apt  75     1               340                2020-08-01   4.75               1                               265                 1
5121      BlissArtsSpace!                                     7356       Garon        Brooklyn             Bedford-Stuyvesant  40.68688  -73.95596  Private room     60     29              50                 2019-12-02   0.37               1                               365                 1
5803      Lovely Room 1, Garden, Best Area, Legal rental      9744       Laurie       Brooklyn             South Slope         40.66829  -73.98779  Private room     88     4               180                2020-03-18   1.31               3                               344                 1
10452     Large B&B Style rooms                               35935      Angela       Brooklyn             Bedford-Stuyvesant  40.68310  -73.95473  Private room     70     3               75                 2019-10-12   0.60               2                               365                 1
10962     Lovely Room 2; Garden; Best area, Legal             9744       Laurie       Brooklyn             South Slope         40.66869  -73.98780  Private room     88     4               180                2020-08-03   1.36               3                               365                 1
                                                                                                                                                                                                                                                                                                  ..
44414370  Fantastic room close to Subways toward Manhattan!   294748832  Bruna        Brooklyn             Bedford-Stuyvesant  40.68064  -73.91836  Private room     42     1               1                  2020-07-30   1.00               4                               178                 1
44419098  Über Cozy room in Bushwick                          3731024    Andrew       Brooklyn             Bushwick            40.69702  -73.93239  Private room     65     2               1                  2020-08-09   1.00               1                               365                 1
44435099  Private Room in Apartment You Can Rent in Brooklyn  358933697  Kenday       Brooklyn             East New York       40.67210  -73.87946  Private room     45     1               1                  2020-07-29   1.00               1                               344                 1
44609727  Private room in a big apartment in Brooklyn         310776840  Alejandra    Brooklyn             Bedford-Stuyvesant  40.69146  -73.93433  Private room     40     1               1                  2020-08-09   1.00               4                               228                 1
44633340  C.C - Brklyn Small but cozy room close to Subways   361101225  Roger        Brooklyn             Bushwick            40.68650  -73.90841  Private room     46     1               1                  2020-08-10   1.00               4                               364                 1
Name: count, Length: 8234, dtype: int64

In [9]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
names = ["Michael", "David", "John", "Daniel"]

condition = df["host_name"].isin(names)
df[condition].value_counts()

id        name                                                host_id    host_name  neighbourhood_group  neighbourhood              latitude  longitude  room_type        price  minimum_nights  number_of_reviews  last_review  reviews_per_month  calculated_host_listings_count  availability_365
16595     LOFT HAVEN ~ Six Windows ~ Bricks ~ Plants ~ Quiet  64522      Daniel     Brooklyn             Williamsburg               40.70933  -73.96792  Entire home/apt  271    1               172                2020-07-14   1.44               1                               365                 1
61747     Cozy,  Brooklyn, Prospect Park Studio               299370     David      Brooklyn             Prospect-Lefferts Gardens  40.65979  -73.96180  Entire home/apt  91     14              97                 2018-01-31   0.83               1                               44                  1
62903     Beautiful modern studio apartment in heart of NYC   306605     Daniel     Manhattan            Chelsea                    40.74238  -73.99567  Entire home/apt  205    15              68                 2019-12-14   0.67               2                               89                  1
74073     Food & Music Dream Apartment in Williamsburg        211877     Daniel     Brooklyn             Williamsburg               40.71113  -73.96054  Entire home/apt  187    30              90                 2020-07-31   0.81               1                               261                 1
138216    Sunny and Spacious Designer's Home                  674970     Michael    Brooklyn             Greenpoint                 40.72212  -73.94254  Entire home/apt  100    6               9                  2019-09-20   0.17               1                               0                   1
                                                                                                                                                                                                                                                                                                       ..
44081738  Smart & Safe entire home in Staten Island NY        352065598  Daniel     Staten Island        Oakwood                    40.56137  -74.10729  Entire home/apt  70     1               1                  2020-08-09   1.00               1                               256                 1
44088976  Spacious oasis - office, private garden, parking    1704370    David      Brooklyn             Clinton Hill               40.68574  -73.96126  Entire home/apt  140    3               1                  2020-07-25   1.00               1                               17                  1
44131715  Spotless upper east side full 1 bedroom apartment   118744531  Daniel     Manhattan            Upper East Side            40.76865  -73.95250  Entire home/apt  105    3               2                  2020-08-01   2.00               1                               43                  1
44340349  Private Bedroom at a Great Location!!               303446068  John       Manhattan            Upper East Side            40.76150  -73.96198  Private room     81     6               1                  2020-07-29   1.00               1                               365                 1
44662157  Flushing Sunshine home #102                         361579037  Daniel     Queens               Flushing                   40.74441  -73.82829  Private room     55     1               3                  2020-08-16   3.00               2                               365                 1
Name: count, Length: 948, dtype: int64

In [12]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

condition = df['neighbourhood'] == 'Williamsburg'
df["adjusted_price"] = np.where(condition, df['price'] + 100, df['price'])
df["adjusted_price"]

0        175
1         75
2         60
3        175
4         65
        ...
46522    145
46523     87
46524     59
46525     80
46526     66
Name: adjusted_price, Length: 46527, dtype: int64

In [16]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

df["room_type"].value_counts(normalize=True) * 100

room_type
Entire home/apt    51.578653
Private room       45.444581
Shared room         2.121349
Hotel room          0.855417
Name: proportion, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [19]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

listings = df.groupby('neighbourhood_group')
listings['price'].count()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
Name: price, dtype: int64

In [20]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

listings = df.groupby('neighbourhood_group')
listings['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [ ]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
listings = df.groupby('room_type')
listings['price'].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [26]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 

listings = df.groupby('neighbourhood_group')
listings['price'].agg(['min','max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [27]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
groupby_cols = ['neighbourhood_group', 'room_type']
groups = df.groupby(groupby_cols)
groups['price'].mean()

neighbourhood_group  room_type
Bronx                Entire home/apt    138.004819
                     Private room        68.419668
                     Shared room         66.391304
Brooklyn             Entire home/apt    171.587687
                     Hotel room         147.300000
                     Private room        71.291189
                     Shared room         57.870091
Manhattan            Entire home/apt    231.335572
                     Hotel room         292.515670
                     Private room       128.277069
                     Shared room        111.735084
Queens               Entire home/apt    150.168900
                     Hotel room         139.058824
                     Private room        69.972564
                     Shared room         89.891892
Staten Island        Entire home/apt    151.720930
                     Private room        70.312883
                     Shared room         46.000000
Name: price, dtype: float64

In [32]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

groupby_cols = ['neighbourhood_group', 'room_type']
groups = df.groupby(groupby_cols)
groups['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819   103.0
                    Private room       722   16    700   68.419668    55.0
                    Shared room         46   20    800   66.391304    44.0
Brooklyn            Entire home/apt   9112   20  10000  171.587687   135.0
                    Hotel room          30    0    399  147.300000   129.0
                    Private room      9159   10   2500   71.291189    60.0
                    Shared room        331   15   1500   57.870091    36.0
Manhattan           Entire home/apt  12209    0  10000  231.335572   165.0
                    Hotel room         351    0   2211  292.515670   210.0
                    Private room      7601   10  10000  128.277069    80.0
                    Shared room        419   10  10000  111.735084    60.0
Queens              Entire home/apt   2090   10  10000  150.168900   115.0
                    Hotel room          17    0    249  139.058824   149.0
                    Private room      3499   18   9000   69.972564    55.0
                    Shared room        185   14   3000   89.891892    40.0
Staten Island       Entire home/apt    172   39   1200  151.720930   111.0
                    Private room       163   20    800   70.312883    55.0
                    Shared room          6   19     82   46.000000    38.0

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [5]:
# 1. Load the `prices.csv` and the `n_listings.csv`
prices = pd.read_csv("/workspaces/ds-fall-2026/Week-01-Pandas/data/prices.csv")
n_listings = pd.read_csv("/workspaces/ds-fall-2026/Week-01-Pandas/data/n_listings.csv", sep=';')

prices.info()
n_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  5 non-null      str
 1    mean_price          5 non-null      float64
dtypes: float64(1), str(1)
memory usage: 212.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  4 non-null      str
 1   n_listings           4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [7]:
# 2. Do join that keeps all the records for each table.

merged = pd.merge(
    prices, 
    n_listings, 
    on = "neighbourhood_group",
    how = "outer")

In [15]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
file_path = "/workspaces/ds-fall-2026/Week-01-Pandas/data/joined.csv"
merged.to_csv(file_path, index=False)

In [16]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
loaded = pd.read_csv(file_path)
loaded.info()
loaded.value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  6 non-null      str
 1    mean_price          5 non-null      float64
 2   n_listings           4 non-null      float64
dtypes: float64(2), str(1)
memory usage: 276.0 bytes

neighbourhood_group   mean_price  n_listings
Bronx                92.751479    1183.0        1
Brooklyn             120.225258   18632.0       1
Manhattan            191.880466   20580.0       1
Name: count, dtype: int64

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.