# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name 
print("w hussam version control explanation")

w hussam version control explanation

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /workspaces/ds-fall-2026/.venv/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /workspaces/ds-fall-2026/.venv/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/ds-fall-2026/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspaces/ds-fall-2026/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [3]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [4]:
# Load data here
df = pd.read_csv("../data/listings.csv")

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [11]:
# 1. How many listings are there with a price less than 100? 
(df["price"] < 100).sum()

np.int64(22778)

In [16]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk = df[df["neighbourhood_group"]=="Brooklyn"]
len(df_bk)

18632

In [17]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

(df_bk["price"] < 100).sum()

np.int64(10473)

In [18]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
names = ["Michael", "David", "John", "Daniel"]

(df["host_name"].isin(names)).sum()

np.int64(1258)

In [22]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

df["adjusted_price"] = np.where(
    df["neighbourhood"]=="Williamsburg",
    df["price"]+100,
    df["price"]
)

In [ ]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

# ill assume that the entire apt/home and hotel wtv categories are separate from the 2 being asked
private = (df["room_type"] == "Private room").mean() * 100
shared = (df["room_type"] == "Shared room").mean() * 100
print(f"Private: {private}\n Shared: {shared}")

Private: 45.444580566122895
 Shared: 2.12134889419047

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [33]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

df.groupby("neighbourhood_group").size()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [34]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

df.groupby("neighbourhood_group")["price"].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [35]:
# 2.5. Using `groupby`, find the mean price for each room_type. 

df.groupby("room_type")["price"].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [40]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 

df.groupby("neighbourhood_group")["price"].agg(["min","max"])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [42]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

df.groupby(["room_type","neighbourhood_group"])["price"].mean()

room_type        neighbourhood_group
Entire home/apt  Bronx                  138.004819
                 Brooklyn               171.587687
                 Manhattan              231.335572
                 Queens                 150.168900
                 Staten Island          151.720930
Hotel room       Brooklyn               147.300000
                 Manhattan              292.515670
                 Queens                 139.058824
Private room     Bronx                   68.419668
                 Brooklyn                71.291189
                 Manhattan              128.277069
                 Queens                  69.972564
                 Staten Island           70.312883
Shared room      Bronx                   66.391304
                 Brooklyn                57.870091
                 Manhattan              111.735084
                 Queens                  89.891892
                 Staten Island           46.000000
Name: price, dtype: float64

In [43]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

df.groupby(["room_type","neighbourhood_group"])["price"].agg(["size","min","max","mean","median","std"])

                                      size  min    max        mean  median  \
room_type       neighbourhood_group
Entire home/apt Bronx                  415   25   1404  138.004819   103.0
                Brooklyn              9112   20  10000  171.587687   135.0
                Manhattan            12209    0  10000  231.335572   165.0
                Queens                2090   10  10000  150.168900   115.0
                Staten Island          172   39   1200  151.720930   111.0
Hotel room      Brooklyn                30    0    399  147.300000   129.0
                Manhattan              351    0   2211  292.515670   210.0
                Queens                  17    0    249  139.058824   149.0
Private room    Bronx                  722   16    700   68.419668    55.0
                Brooklyn              9159   10   2500   71.291189    60.0
                Manhattan             7601   10  10000  128.277069    80.0
                Queens                3499   18   9000   69.972564    55.0
                Staten Island          163   20    800   70.312883    55.0
Shared room     Bronx                   46   20    800   66.391304    44.0
                Brooklyn               331   15   1500   57.870091    36.0
                Manhattan              419   10  10000  111.735084    60.0
                Queens                 185   14   3000   89.891892    40.0
                Staten Island            6   19     82   46.000000    38.0

                                            std
room_type       neighbourhood_group
Entire home/apt Bronx                126.032106
                Brooklyn             236.732843
                Manhattan            410.306439
                Queens               252.606739
                Staten Island        147.518392
Hotel room      Brooklyn              91.153206
                Manhattan            315.924085
                Queens                50.743806
Private room    Bronx                 57.337866
                Brooklyn              69.023165
                Manhattan            448.677306
                Queens               163.814468
                Staten Island         70.759593
Shared room     Bronx                114.442703
                Brooklyn              92.217618
                Manhattan            502.728868
                Queens               275.675158
                Staten Island         28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [47]:
# 1. Load the `prices.csv` and the `n_listings.csv`
df_p = pd.read_csv("../data/prices.csv")
df_n = pd.read_csv("../data/n_listings.csv", sep=";")

In [49]:
# 2. Do join that keeps all the records for each table.

df_m = pd.merge(df_p, df_n, on="neighbourhood_group", how="outer")
df_m

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN
5       Staten Island   110.947214         NaN

In [50]:
# 3. Save your joined csv as `joined.csv` into the data folder. 

df_m.to_csv("../data/joined.csv", index=False)

In [ ]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.