# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Import here.
# Axel Mizerovskiy
import numpy as np
import pandas as pd

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [3]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [5]:
# Count by hand. (lol kidding)
# df_food.count()
df_food.shape

(125, 61)

What are the columns and their types in this data set?

In [5]:
# Show the column names and their types.

df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [14]:
# Remove ‘em.
cols_to_keep = ['Gender', 'calories_day', 'weight']
df_clean = df_food[cols_to_keep]

What about `NaN`s? How many are there?

In [15]:
# Count ‘em.
df_clean.isna().sum()

Gender           0
calories_day    19
weight           2
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [20]:
# Drop ‘em.
df_clean = df_clean.dropna()
df_clean

     Gender  calories_day                    weight
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
5         1           3.0                       190
..      ...           ...                       ...
118       1           3.0                       140
119       2           3.0                       185
120       1           4.0                       156
121       1           2.0                       180
123       2           4.0                       135

[104 rows x 3 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [23]:
# Fix that.
#df_clean['weight'] = df_clean['weight'].astype('int')    doesnt work since doesnt drop
df_clean['weight'] = pd.to_numeric(df_clean['weight'], errors='coerce') # turns bad strings to NaN
df_clean = df_clean.dropna() # drops NaNs
df_clean['weight'] = df_clean['weight'].astype(int) # tuns into int
df_clean

     Gender  calories_day  weight
1         1           3.0     155
4         1           2.0     190
5         1           3.0     190
6         2           3.0     180
7         1           3.0     137
..      ...           ...     ...
118       1           3.0     140
119       2           3.0     185
120       1           4.0     156
121       1           2.0     180
123       2           4.0     135

[101 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [ ]:
# Savey save!
#df_clean.to_csv('food_cleaned.csv', index = True)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [27]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salary = pd.read_csv('/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [28]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [33]:
# Show the column names and their types.
df_salary.dtypes
#len(df_salary.columns)

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [35]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed, gender, race
df_salary.columns = [
    'timestamp', 'age', 'industry', 'title', 'title_context',
    'salary', 'additional_compensation', 'currency', 'other_currency',
    'salary_context', 'country', 'state', 'city', 'total_yoe',
    'field_yoe', 'highest_education_completed', 'gender', 'race'
]
df_salary.dtypes

timestamp                          str
age                                str
industry                           str
title                              str
title_context                      str
salary                             str
additional_compensation        float64
currency                           str
other_currency                     str
salary_context                     str
country                            str
state                              str
city                               str
total_yoe                          str
field_yoe                          str
highest_education_completed        str
gender                             str
race                               str
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [36]:
# List the unique industries and a count of their instances.
pd.unique(df_salary['industry'])

<StringArray>
[                'Education (Higher Education)',
                            'Computing or Tech',
                'Accounting, Banking & Finance',
                                   'Nonprofits',
                                   'Publishing',
                'Education (Primary/Secondary)',
                                          'Law',
                                  'Health care',
               'Utilities & Telecommunications',
                       'Business or Consulting',
 ...
                       'Hardware Manufacturing',
                        'Real Estate / Housing',
                               'Research / Gov',
                                      'Biology',
                            'Undergrad student',
                        'Concrete Construction',
                                     'Plumbing',
 'I'm currently a student and don't have a job',
                                     'Student ',
                               'Wine & Spirits']
Length: 1220, dtype: str

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [38]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [ ]:
# Sanity Check 
df_salary_tech.describe

timestamp                          str
age                                str
industry                           str
title                              str
title_context                      str
salary                             str
additional_compensation        float64
currency                           str
other_currency                     str
salary_context                     str
country                            str
state                              str
city                               str
total_yoe                          str
field_yoe                          str
highest_education_completed        str
gender                             str
race                               str
dtype: object

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [45]:
# Filtery filter for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']
df_salary_tech[:5]

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [54]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
pd.unique(df_salary_tech['country'])
df_salary_tech['country'].value_counts()

# United States,US,USA,usa,U.S.
# ,America,United States of America,United states ,United State, U.S.A., U.S.A. ,

country
US                      3726
Canada                     5
Israel                     5
Australia                  2
India                      2
Spain                      2
Brazil                     2
United Kingdom             2
New Zealand                2
Poland                     2
France                     2
Nigeria                    2
Cuba                       1
Danmark                    1
Italy                      1
International              1
Remote (philippines)       1
Singapore                  1
Uruguay                    1
Mexico                     1
singapore                  1
Pakistan                   1
Netherlands                1
China                      1
Romania                    1
Japan                      1
Australian                 1
Denmark                    1
Jamaica                    1
Thailand                   1
Colombia                   1
denmark                    1
Ghana                      1
ss                         1
Burma                      1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [ ]:
# Replace them all with 'US'.
# ill try to replace mmore than top 5 just for fun
# fully ai for this just to grab all the variation of it 
us_variants = [
    'United State of America', 'Uniyed states', 'Unite States',
    'United State', 'UnitedStates', 'United Stated', 'U.S',
    'United Stateds', 'San Francisco', 'U.S.A', 'United Stares',
    'Unites States', 'U.S.A ', 'ISA', 'Puerto Rico '
]
df_salary_tech['country'] = df_salary_tech['country'].astype(str).str.strip()
df_salary_tech['country'] = df_salary_tech['country'].replace(
    [s.strip() for s in us_variants], 
    'US'
)
pd.unique(df_salary_tech['country'])

country
US                      3726
Canada                     5
Israel                     5
Australia                  2
India                      2
Spain                      2
Brazil                     2
United Kingdom             2
New Zealand                2
Poland                     2
France                     2
Nigeria                    2
Cuba                       1
Danmark                    1
Italy                      1
International              1
Remote (philippines)       1
Singapore                  1
Uruguay                    1
Mexico                     1
singapore                  1
Pakistan                   1
Netherlands                1
China                      1
Romania                    1
Japan                      1
Australian                 1
Denmark                    1
Jamaica                    1
Thailand                   1
Colombia                   1
denmark                    1
Ghana                      1
ss                         1
Burma                      1
Name: count, dtype: int64

Have a look at the count of each unique country again now.

In [ ]:
# Count again.
df_salary_tech['country'].value_counts()

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
# there are only a couple of variants so i dont see why not just list them all

In [ ]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [60]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech_us = df_salary_tech[df_salary_tech['country'] == 'US']
#df_salary_tech_us.dtypes
df_salary_tech_us['salary'] = pd.to_numeric(df_salary_tech_us['salary'], errors='coerce') # cause its a str

state_salaries = (
    df_salary_tech_us
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values(by='mean', ascending=False)
)

print(state_salaries)

                                  min      mean        max
state
Michigan, Texas, Washington  340000.0  340000.0   340000.0
Florida                       28800.0  210711.0  2600000.0
California, Oregon           200000.0  200000.0   200000.0
California, Colorado         176000.0  176000.0   176000.0
Delaware                     169000.0  169000.0   169000.0
...                               ...       ...        ...
Mississippi                       NaN       NaN        NaN
New York, Texas                   NaN       NaN        NaN
North Dakota                      NaN       NaN        NaN
South Dakota                      NaN       NaN        NaN
Utah, Vermont                     NaN       NaN        NaN

[66 rows x 3 columns]

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [ ]:
# Fix it.
# i didnt forgot i checked

Let’s try that again.

In [ ]:
# Try it again. Yeah!
# no need, im a goat

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [67]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech_us['timestamp'] = pd.to_datetime(df_salary_tech_us['timestamp'])
df_stu_2023 = df_salary_tech_us[df_salary_tech_us['timestamp'].dt.year.isin([2021, 2022, 2023])].copy()

state_salaries = (
    df_stu_2023
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values(by='mean', ascending=False)
)

print(state_salaries[:40])

                                     min           mean       max
state
Michigan, Texas, Washington     340000.0  340000.000000  340000.0
California, Oregon              200000.0  200000.000000  200000.0
California, Colorado            176000.0  176000.000000  176000.0
Delaware                        169000.0  169000.000000  169000.0
Connecticut                      68000.0  161610.000000  270000.0
California                           0.0  153754.893258  520000.0
New York                         14000.0  146594.112150  590000.0
Wisconsin                            1.0  145806.888889  920000.0
District of Columbia             59000.0  142923.076923  200000.0
Alabama                          52000.0  138000.000000  350000.0
New Jersey, New York            135000.0  137500.000000  140000.0
Washington                          72.0  137427.774648  300000.0
Ohio                             42000.0  137066.666667  954000.0
Massachusetts                    41000.0  125660.986842  400000.0
Nevada                          107100.0  124550.000000  142000.0
New Jersey                       67500.0  124090.909091  192000.0
Oregon                           16200.0  122640.000000  230000.0
West Virginia                   120000.0  120000.000000  120000.0
Maryland                         62000.0  119955.461538  176000.0
Illinois                         36000.0  119248.382353  228800.0
Louisiana, Washington           117000.0  117000.000000  117000.0
Pennsylvania                     52000.0  116826.388889  237000.0
Georgia                          29120.0  115488.484848  242000.0
Virginia                         58750.0  115086.696970  378000.0
Montana                          65000.0  112666.666667  145000.0
Kansas                           41500.0  109666.666667  167000.0
Colorado                         49400.0  109291.891892  165000.0
District of Columbia, Virginia  109200.0  109200.000000  109200.0
Vermont                          91250.0  105625.000000  120000.0
Idaho                            74860.0  105465.000000  170000.0
Utah                             33280.0  105023.333333  176000.0
Maine                            50000.0  103833.333333  173000.0
Texas                            10700.0  103685.245902  190000.0
Kentucky                         62000.0  102500.000000  125000.0
Minnesota                        52124.0  102381.500000  210000.0
Florida                          28800.0  102106.954545  170000.0
Iowa                             63000.0  101200.000000  142000.0
Rhode Island                     76000.0   99475.000000  122950.0
Arizona                          35000.0   97833.333333  145000.0
North Carolina                   29000.0   97250.000000  165000.0

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)